from alembic import command
from fastapi.testclient import TestClient
from sqlalchemy import Engine

from tests.api.conftest import alembic_config


def test_health_reports_database(client: TestClient) -> None:
    response = client.get("/api/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok", "database": "ok"}


def test_migrations_match_models(engine: Engine, database_url: str) -> None:
    # Fails with AutogenerateDiffsDetected when a model change has no migration.
    command.check(alembic_config(database_url))
