"""Training analytics: load the log, compute metrics and suggest progressions."""

from gym_tracker.analysis.loader import SCHEMAS, TrainingLog, load_training_log
from gym_tracker.analysis.metrics import (
    detect_plateaus,
    estimate_1rm,
    personal_records,
    session_bests,
    weekly_volume_by_muscle,
    weekly_weight_change,
    weight_trend,
    working_sets,
)
from gym_tracker.analysis.recommendations import (
    DEFAULT_VOLUME_RULES,
    Action,
    PerformedSet,
    PlannedSet,
    Progression,
    ProgressionRules,
    Reason,
    Recommendation,
    VolumeAdvice,
    VolumeRules,
    VolumeStatus,
    decide_progression,
    load_increment,
    recommend,
    volume_advice,
)

__all__ = [
    "DEFAULT_VOLUME_RULES",
    "SCHEMAS",
    "Action",
    "PerformedSet",
    "PlannedSet",
    "Progression",
    "ProgressionRules",
    "Reason",
    "Recommendation",
    "TrainingLog",
    "VolumeAdvice",
    "VolumeRules",
    "VolumeStatus",
    "decide_progression",
    "detect_plateaus",
    "estimate_1rm",
    "load_increment",
    "load_training_log",
    "personal_records",
    "recommend",
    "session_bests",
    "volume_advice",
    "weekly_volume_by_muscle",
    "weekly_weight_change",
    "weight_trend",
    "working_sets",
]
