"""plan routine targets per set

Moves the per-exercise targets (sets x reps at one weight) to one row per planned set, so a routine
can ramp the weight or the reps from set to set. Existing targets are expanded into identical sets.

Revision ID: f2aa6d776f7e
Revises: f2043aa6a8c2
Create Date: 2026-09-16 13:23:25.220908

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2aa6d776f7e"
down_revision: str | Sequence[str] | None = "f2043aa6a8c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routine_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("routine_exercise_id", sa.Integer(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("target_reps", sa.Integer(), nullable=True),
        sa.Column("target_weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("target_rpe", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.CheckConstraint("set_number > 0", name=op.f("ck_routine_sets_set_number_positive")),
        sa.CheckConstraint("target_reps > 0", name=op.f("ck_routine_sets_target_reps_positive")),
        sa.CheckConstraint("target_rpe BETWEEN 1 AND 10", name=op.f("ck_routine_sets_target_rpe_range")),
        sa.CheckConstraint("target_weight_kg >= 0", name=op.f("ck_routine_sets_target_weight_non_negative")),
        sa.ForeignKeyConstraint(
            ["routine_exercise_id"],
            ["routine_exercises.id"],
            name=op.f("fk_routine_sets_routine_exercise_id_routine_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routine_sets")),
        sa.UniqueConstraint(
            "routine_exercise_id", "set_number", name=op.f("uq_routine_sets_routine_exercise_id_set_number")
        ),
    )
    # A slot with targets but no set count becomes a single set; a slot without targets gets none.
    op.execute(
        """
        INSERT INTO routine_sets (routine_exercise_id, set_number, target_reps, target_weight_kg, target_rpe)
        SELECT re.id, set_number, re.target_reps, re.target_weight_kg, re.target_rpe
        FROM routine_exercises AS re
        CROSS JOIN LATERAL generate_series(
            1,
            COALESCE(
                re.target_sets,
                CASE WHEN COALESCE(re.target_reps, re.target_weight_kg, re.target_rpe) IS NULL THEN 0 ELSE 1 END
            )
        ) AS set_number
        """
    )
    op.drop_column("routine_exercises", "target_rpe")
    op.drop_column("routine_exercises", "target_reps")
    op.drop_column("routine_exercises", "target_weight_kg")
    op.drop_column("routine_exercises", "target_sets")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routine_exercises", sa.Column("target_sets", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "routine_exercises",
        sa.Column("target_weight_kg", sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    )
    op.add_column("routine_exercises", sa.Column("target_reps", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "routine_exercises",
        sa.Column("target_rpe", sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    )
    op.create_check_constraint(
        op.f("ck_routine_exercises_target_sets_positive"), "routine_exercises", "target_sets > 0"
    )
    op.create_check_constraint(
        op.f("ck_routine_exercises_target_reps_positive"), "routine_exercises", "target_reps > 0"
    )
    op.create_check_constraint(
        op.f("ck_routine_exercises_target_weight_non_negative"), "routine_exercises", "target_weight_kg >= 0"
    )
    op.create_check_constraint(
        op.f("ck_routine_exercises_target_rpe_range"), "routine_exercises", "target_rpe BETWEEN 1 AND 10"
    )
    # Lossy: keeps the set count and the targets of the first set.
    op.execute(
        """
        UPDATE routine_exercises AS re
        SET target_sets = planned.sets,
            target_reps = first_set.target_reps,
            target_weight_kg = first_set.target_weight_kg,
            target_rpe = first_set.target_rpe
        FROM (SELECT routine_exercise_id, count(*) AS sets FROM routine_sets GROUP BY routine_exercise_id) AS planned
        JOIN routine_sets AS first_set
            ON first_set.routine_exercise_id = planned.routine_exercise_id AND first_set.set_number = 1
        WHERE re.id = planned.routine_exercise_id
        """
    )
    op.drop_table("routine_sets")
    # ### end Alembic commands ###
